################################################
#                                              #
#                 StatsAPI v2                  #
#                Made by DevSnx                #
#                                              #
################################################

database:
  # Type: sqlite for flatfile, and mysql for an external database.
  Type: 'sqlite'
  # Only edit if Type is 'mysql' or 'mongodb'.
  mysql:
    # name of your database
    database: 'statsapi'
    # ip of your MySQL database
    host: 'localhost'
    # port of your MySQL/Mongodb database, commonly is 3306/27017
    port: 3306
    # username of your MySQL database
    username: 'user'
    # password of your MySQL database
    password: 'root'
    # use SSL or NOT in MySQL database connection
    useSSL: false

command:
  enable: true
  # If set to true players will need a permission to use the command /stats
  userpermissions:
    enable: true
    permission: statsapi.stats

message:
  no_permissions: 'no permissions for this command'
  no_uuid: 'the player %PLAYER% not exists'
  no_stats: 'No stats avaible'
  stats_from_me:
    - 'My Stats'
    - 'Kills: %KILLS%'
    - 'Deaths: %DEATHS%'
  stats_from_other:
    - 'Stats from %PLAYER%'
    - 'Kills: %KILLS%'
    - 'Deaths: %DEATHS%'