##################################
#                                #
#     Configuration StatsAPI     #
#          DevSnx   v2           #
#                                #
##################################

# for Mysql use: mysql
# for sqllite use: sqllite
savetyp: mysql

# database login settings
databse:
  host: localhost
  port: 3306
  user: statsapi
  password: statsapi
  database: statsapi

# Settings
command:
# disable or enable the /stats and /stats <Player> command
  stats: enable

# enable or disable the permissions for use the commands
permissions: enable
permission:
  stats_from_me: stats.me
  stats_from_other: stats.other

# Change the Messages for /stats
message:
  no_permissions: 'no permissions for this command'
  no_uuid: 'the player %PLAYER% not exists'
  no_stats_from_me: 'No stats avaible'
  no_stats_from_other: 'No stats avaible from %PLAYER%'
  stats_from_me:
    - 'My Stats'
    - 'Kills: %KILLS%'
    - 'Deaths: %DEATHS%'
  stats_from_other:
    - 'Stats from %PLAYER%'
    - 'Kills: %KILLS%'
    - 'Deaths: %DEATHS%'